// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Awards documents
 */
interface AwardsDocumentData {
  /**
   * Award Title field in *Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Golden Glove
   * - **API ID Path**: awards.award_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  award_title: prismic.KeyTextField;

  /**
   * Award Subtitle field in *Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2025 Season
   * - **API ID Path**: awards.award_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  award_subtitle: prismic.KeyTextField;

  /**
   * Player Name field in *Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Player Name
   * - **API ID Path**: awards.player_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  player_name: prismic.KeyTextField;

  /**
   * Player Team field in *Awards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.player_team
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  player_team: ContentRelationshipFieldWithData<
    [{ id: "team"; fields: ["name", "logo"] }]
  >;

  /**
   * Sort Order field in *Awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1
   * - **API ID Path**: awards.sort_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sort_order: prismic.KeyTextField;
}

/**
 * Awards document from Prismic
 *
 * - **API ID**: `awards`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AwardsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AwardsDocumentData>, "awards", Lang>;

type BlogDocumentDataSlicesSlice = never;

/**
 * Item in *blog → Matches*
 */
export interface BlogDocumentDataMatchesItem {
  /**
   * Match field in *blog → Matches*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.matches[].match
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  match: ContentRelationshipFieldWithData<
    [{ id: "match"; fields: ["opta_id"] }]
  >;
}

/**
 * Item in *blog → Teams*
 */
export interface BlogDocumentDataTeamsItem {
  /**
   * Team field in *blog → Teams*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.teams[].team
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  team: ContentRelationshipFieldWithData<
    [
      {
        id: "team";
        fields: [
          "opta_id",
          "name",
          "key",
          "country",
          "logo",
          "country_code",
          "color_primary",
          "color_secondary",
          "alphabetical_sort_string",
        ];
      },
    ]
  >;
}

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog title
   * - **API ID Path**: blog.title
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * excerpt field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.excerpt
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * content field in *blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.content
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Media & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  image: prismic.ImageField<never>;

  /**
   * category field in *blog*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.category
   * - **Tab**: Media & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Announcements"
    | "Tournament Recap"
    | "Match Recap"
    | "Social Impact"
    | "Match Day Preview"
  >;

  /**
   * date field in *blog*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.date
   * - **Tab**: Media & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * author field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.author
   * - **Tab**: Media & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField /**
   * Tournament field in *blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.tournament
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  tournament: prismic.ContentRelationshipField<"tournament">;

  /**
   * Matches field in *blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.matches[]
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  matches: prismic.GroupField<Simplify<BlogDocumentDataMatchesItem>>;

  /**
   * Teams field in *blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.teams[]
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  teams: prismic.GroupField<Simplify<BlogDocumentDataTeamsItem>>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Content for Broadcast Partner documents
 */
interface BroadcastPartnersDocumentData {
  /**
   * Name field in *Broadcast Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.name
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField /**
   * Logo field in *Broadcast Partner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.logo
   * - **Tab**: Logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  logo: prismic.ImageField<never>;

  /**
   * Logo White field in *Broadcast Partner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.logo_white
   * - **Tab**: Logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_white: prismic.ImageField<never>;

  /**
   * Icon Logo field in *Broadcast Partner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.icon_logo
   * - **Tab**: Logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_logo: prismic.ImageField<never>;

  /**
   * Logo on Primary field in *Broadcast Partner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.logo_on_primary
   * - **Tab**: Logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_on_primary: prismic.ImageField<never> /**
   * Color Primary field in *Broadcast Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.color_primary
   * - **Tab**: Brand Colors
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  color_primary: prismic.KeyTextField;

  /**
   * Color Secondary field in *Broadcast Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.color_secondary
   * - **Tab**: Brand Colors
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color_secondary: prismic.KeyTextField /**
   * Streaming Link field in *Broadcast Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast_partners.streaming_link
   * - **Tab**: Links
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  streaming_link: prismic.KeyTextField;
}

/**
 * Broadcast Partner document from Prismic
 *
 * - **API ID**: `broadcast_partners`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BroadcastPartnersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BroadcastPartnersDocumentData>,
    "broadcast_partners",
    Lang
  >;

/**
 * Item in *Faq Section → FAQs*
 */
export interface FaqSectionDocumentDataFaqsItem {
  /**
   * Question field in *Faq Section → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq Section → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Content for Faq Section documents
 */
interface FaqSectionDocumentData {
  /**
   * Section title field in *Faq Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.section_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section order field in *Faq Section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.section_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  section_order: prismic.NumberField;

  /**
   * FAQs field in *Faq Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.faqs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqSectionDocumentDataFaqsItem>>;
}

/**
 * Faq Section document from Prismic
 *
 * - **API ID**: `faq_section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqSectionDocumentData>,
    "faq_section",
    Lang
  >;

/**
 * Content for Image with text documents
 */
interface ImageWithTextDocumentData {
  /**
   * heading field in *Image with text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.heading
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * title field in *Image with text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.title
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Image with text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.description
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField /**
   * image field in *Image with text*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.image
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  image: prismic.ImageField<never> /**
   * align image field in *Image with text*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.align_image
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  align_image: prismic.SelectField<"left" | "right">;
}

/**
 * Image with text document from Prismic
 *
 * - **API ID**: `image_with_text`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageWithTextDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImageWithTextDocumentData>,
    "image_with_text",
    Lang
  >;

/**
 * Item in *Match → Broadcasts*
 */
export interface MatchDocumentDataBroadcastsItem {
  /**
   * Streaming Service field in *Match → Broadcasts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: match.broadcasts[].streaming_service
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  streaming_service: ContentRelationshipFieldWithData<
    [
      {
        id: "broadcast_partners";
        fields: [
          "name",
          "logo",
          "logo_white",
          "icon_logo",
          "logo_on_primary",
          "color_primary",
          "color_secondary",
          "streaming_link",
        ];
      },
    ]
  >;
}

type MatchDocumentDataSlicesSlice = never;

/**
 * Content for Match documents
 */
interface MatchDocumentData {
  /**
   * Match Number field in *Match*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: match.match_number
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  match_number: prismic.NumberField;

  /**
   * Stage field in *Match*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: match.stage
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  stage: prismic.SelectField<"Group Stage" | "Knockout Stage">;

  /**
   * Knockout Stage Match Type field in *Match*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: match.knockout_stage_match_type
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  knockout_stage_match_type: prismic.SelectField<
    "Group 1 Semifinal" | "Group 2 Semifinal" | "Third Place Match" | "Final"
  > /**
   * Start Time field in *Match*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: match.start_time
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */;
  start_time: prismic.TimestampField /**
   * Home Team field in *Match*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: match.home_team
   * - **Tab**: Teams
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  home_team: ContentRelationshipFieldWithData<
    [
      {
        id: "team";
        fields: [
          "opta_id",
          "name",
          "key",
          "country",
          "country_code",
          "color_primary",
          "logo",
          "color_secondary",
        ];
      },
    ]
  >;

  /**
   * Home Team Name Override field in *Match*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: match.home_team_name_override
   * - **Tab**: Teams
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  home_team_name_override: prismic.KeyTextField;

  /**
   * Away Team field in *Match*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: match.away_team
   * - **Tab**: Teams
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  away_team: ContentRelationshipFieldWithData<
    [
      {
        id: "team";
        fields: [
          "opta_id",
          "name",
          "key",
          "country_code",
          "country",
          "logo",
          "color_primary",
          "color_secondary",
        ];
      },
    ]
  >;

  /**
   * Away Team Name Override field in *Match*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: match.away_team_name_override
   * - **Tab**: Teams
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  away_team_name_override: prismic.KeyTextField /**
   * Tournament field in *Match*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: match.tournament
   * - **Tab**: Tournament & Broadcast
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  tournament: ContentRelationshipFieldWithData<
    [
      {
        id: "tournament";
        fields: [
          "status",
          "prize_pool",
          "country_code",
          "stadium_name",
          "start_date",
          "end_date",
          "number_of_teams",
          "opta_season_id",
          "opta_enabled",
          "opta_competition_id",
        ];
      },
    ]
  >;

  /**
   * Broadcasts field in *Match*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: match.broadcasts[]
   * - **Tab**: Tournament & Broadcast
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  broadcasts: prismic.GroupField<Simplify<MatchDocumentDataBroadcastsItem>> /**
   * Opta ID field in *Match*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: match.opta_id
   * - **Tab**: Data (Opta)
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  opta_id: prismic.KeyTextField /**
   * Slice Zone field in *Match*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: match.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  slices: prismic.SliceZone<MatchDocumentDataSlicesSlice>;
}

/**
 * Match document from Prismic
 *
 * - **API ID**: `match`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MatchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MatchDocumentData>, "match", Lang>;

type PageDocumentDataSlicesSlice =
  | LeadershipGridSlice
  | InfoCardsSlice
  | AccordionSectionSlice
  | CallToActionSlice
  | PartnersSlice
  | TextBlockSlice
  | ImageWithTextSlice
  | HeroSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Player documents
 */
interface PlayerDocumentData {
  /**
   * First Name field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player.first_name
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player.last_name
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_name: prismic.KeyTextField /**
   * Headshot field in *Player*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: player.headshot
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  headshot: prismic.ImageField<never> /**
   * Team field in *Player*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: player.team
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  team: ContentRelationshipFieldWithData<
    [
      {
        id: "team";
        fields: [
          "opta_id",
          "name",
          "key",
          "country",
          "country_code",
          "logo",
          "color_primary",
          "color_secondary",
          "alphabetical_sort_string",
        ];
      },
    ]
  > /**
   * Opta ID field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player.opta_id
   * - **Tab**: Data (Opta)
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  opta_id: prismic.KeyTextField;
}

/**
 * Player document from Prismic
 *
 * - **API ID**: `player`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlayerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PlayerDocumentData>, "player", Lang>;

/**
 * Content for Policy documents
 */
interface PolicyDocumentData {
  /**
   * Policy Name field in *Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Policy name
   * - **API ID Path**: policy.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Policy Content field in *Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: policy.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField /**
   * PDF File field in *Policy*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload PDF file
   * - **API ID Path**: policy.pdf
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */;
  pdf: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Hide From Navigation field in *Policy*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: policy.hide_from_nav
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_from_nav: prismic.BooleanField;

  /**
   * Navigation Order field in *Policy*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Order in navigation (lower numbers first)
   * - **API ID Path**: policy.order
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  order: prismic.NumberField;
}

/**
 * Policy document from Prismic
 *
 * - **API ID**: `policy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PolicyDocumentData>, "policy", Lang>;

/**
 * Content for Sponsor documents
 */
interface SponsorDocumentData {
  /**
   * Name field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.name
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Website Link field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.website_link
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  website_link: prismic.KeyTextField /**
   * Logo field in *Sponsor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.logo
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  logo: prismic.ImageField<never>;

  /**
   * Color Primary field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.color_primary
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color_primary: prismic.KeyTextField;

  /**
   * Color Secondary field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.color_secondary
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color_secondary: prismic.KeyTextField /**
   * Sort Order field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.sort_order
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  sort_order: prismic.KeyTextField;

  /**
   * Visibility field in *Sponsor*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: sponsor.visibility
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  visibility: prismic.BooleanField;
}

/**
 * Sponsor document from Prismic
 *
 * - **API ID**: `sponsor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SponsorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SponsorDocumentData>,
    "sponsor",
    Lang
  >;

/**
 * Item in *Team → Tournaments*
 */
export interface TeamDocumentDataTournamentsItem {
  /**
   * Tournament field in *Team → Tournaments*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.tournaments[].tournament
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tournament: ContentRelationshipFieldWithData<
    [
      {
        id: "tournament";
        fields: [
          "title",
          "country_code",
          "start_date",
          "end_date",
          "opta_competition_id",
          "opta_season_id",
          "opta_enabled",
          "featured",
          "nickname",
        ];
      },
    ]
  >;
}

/**
 * Content for Team documents
 */
interface TeamDocumentData {
  /**
   * Name field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.name
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Key field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.key
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key: prismic.KeyTextField;

  /**
   * Country field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.country
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country: prismic.KeyTextField;

  /**
   * Country Code field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.country_code
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country_code: prismic.KeyTextField /**
   * Logo field in *Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.logo
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  logo: prismic.ImageField<never>;

  /**
   * Color Primary field in *Team*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: team.color_primary
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_primary: prismic.ColorField;

  /**
   * Color Secondary field in *Team*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: team.color_secondary
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_secondary: prismic.ColorField /**
   * Opta ID field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.opta_id
   * - **Tab**: Data & Sorting
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  opta_id: prismic.KeyTextField;

  /**
   * Alphabetical Sort String field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.alphabetical_sort_string
   * - **Tab**: Data & Sorting
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alphabetical_sort_string: prismic.KeyTextField;

  /**
   * Group field in *Team*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: team.group
   * - **Tab**: Data & Sorting
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  group: prismic.SelectField<"Group 1" | "Group 2"> /**
   * Tournaments field in *Team*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.tournaments[]
   * - **Tab**: Tournaments
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  tournaments: prismic.GroupField<Simplify<TeamDocumentDataTournamentsItem>>;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TeamDocumentData>, "team", Lang>;

/**
 * Content for Leadership Member documents
 */
interface TeamMemberDocumentData {
  /**
   * Full Name field in *Leadership Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's full name
   * - **API ID Path**: team_member.name
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role/Position field in *Leadership Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Job title or role
   * - **API ID Path**: team_member.role
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Biography field in *Leadership Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Team member's biography
   * - **API ID Path**: team_member.bio
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField /**
   * Headshot field in *Leadership Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.headshot
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  headshot: prismic.ImageField<"small" | "medium"> /**
   * Display Order field in *Leadership Member*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Order on team page (lower numbers first)
   * - **API ID Path**: team_member.display_order
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/number
   */;
  display_order: prismic.NumberField;

  /**
   * Department field in *Leadership Member*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select department
   * - **API ID Path**: team_member.department
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  department: prismic.SelectField<
    "Player Advisor" | "Co-Founder" | "Leadership Team"
  >;
}

/**
 * Leadership Member document from Prismic
 *
 * - **API ID**: `team_member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamMemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TeamMemberDocumentData>,
    "team_member",
    Lang
  >;

type TournamentDocumentDataSlicesSlice = never;

/**
 * Item in *Tournament → Matches*
 */
export interface TournamentDocumentDataMatchesItem {
  /**
   * Match field in *Tournament → Matches*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.matches[].match
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  match: ContentRelationshipFieldWithData<
    [
      {
        id: "match";
        fields: [
          "match_number",
          {
            id: "home_team";
            customtypes: [
              {
                id: "team";
                fields: [
                  "opta_id",
                  "name",
                  "key",
                  "country",
                  "country_code",
                  "logo",
                  "color_primary",
                  "color_secondary",
                  "alphabetical_sort_string",
                ];
              },
            ];
          },
          "home_team_name_override",
          {
            id: "away_team";
            customtypes: [
              {
                id: "team";
                fields: [
                  "opta_id",
                  "key",
                  "name",
                  "country",
                  "country_code",
                  "logo",
                  "color_primary",
                  "color_secondary",
                  "alphabetical_sort_string",
                ];
              },
            ];
          },
          "away_team_name_override",
          "start_time",
          "stage",
          "knockout_stage_match_type",
          "opta_id",
          {
            id: "broadcasts";
            fields: [
              {
                id: "streaming_service";
                customtypes: [
                  {
                    id: "broadcast_partners";
                    fields: [
                      "name",
                      "logo",
                      "logo_white",
                      "icon_logo",
                      "color_secondary",
                      "logo_on_primary",
                      "color_primary",
                      "streaming_link",
                    ];
                  },
                ];
              },
            ];
          },
        ];
      },
    ]
  >;
}

/**
 * Item in *Tournament → Awards*
 */
export interface TournamentDocumentDataAwardsItem {
  /**
   * Awards field in *Tournament → Awards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.awards[].awards
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  awards: ContentRelationshipFieldWithData<
    [
      {
        id: "awards";
        fields: [
          "award_title",
          "player_name",
          {
            id: "player_team";
            customtypes: [
              {
                id: "team";
                fields: [
                  "name",
                  "logo",
                  "color_primary",
                  "color_secondary",
                  "opta_id",
                  "key",
                  "country_code",
                  "country",
                  "alphabetical_sort_string",
                ];
              },
            ];
          },
          "award_subtitle",
          "sort_order",
          "player_headshot",
        ];
      },
    ]
  >;
}

/**
 * Content for Tournament documents
 */
interface TournamentDocumentData {
  /**
   * Featured field in *Tournament*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tournament.featured
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Status field in *Tournament*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.status
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  status: prismic.SelectField<"Upcoming" | "Live" | "Complete">;

  /**
   * Title field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tournament title
   * - **API ID Path**: tournament.title
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Nickname field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.nickname
   * - **Tab**: General
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nickname: prismic.KeyTextField /**
   * Hero Image field in *Tournament*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.hero_image
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  hero_image: prismic.ImageField<never> /**
   * Prize Pool field in *Tournament*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.prize_pool
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/number
   */;
  prize_pool: prismic.NumberField;

  /**
   * Country Code field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Two-letter country code (e.g., US, UK, FR)
   * - **API ID Path**: tournament.country_code
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country_code: prismic.KeyTextField;

  /**
   * Stadium Name field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.stadium_name
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stadium_name: prismic.KeyTextField;

  /**
   * Start Date field in *Tournament*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.start_date
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Tournament*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.end_date
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Number of Teams field in *Tournament*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.number_of_teams
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number_of_teams: prismic.NumberField;

  /**
   * Tickets Available field in *Tournament*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tournament.tickets_available
   * - **Tab**: Tournament Details
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  tickets_available: prismic.BooleanField /**
   * Recap field in *Tournament*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.recap
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */;
  recap: ContentRelationshipFieldWithData<
    [
      {
        id: "blog";
        fields: ["title", "image", "category", "date", "author", "excerpt"];
      },
    ]
  >;

  /**
   * Highlight Reel Link field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.highlight_reel_link
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlight_reel_link: prismic.KeyTextField;

  /**
   * Know before you go  field in *Tournament*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.know_before_you_go
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  know_before_you_go: prismic.RichTextField;

  /**
   * Know before you go pdf field in *Tournament*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.know_before_you_go_pdf
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  know_before_you_go_pdf: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Slice Zone field in *Tournament*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TournamentDocumentDataSlicesSlice> /**
   * Matches field in *Tournament*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.matches[]
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  matches: prismic.GroupField<Simplify<TournamentDocumentDataMatchesItem>>;

  /**
   * Awards field in *Tournament*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.awards[]
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  awards: prismic.GroupField<Simplify<TournamentDocumentDataAwardsItem>> /**
   * Opta Competition ID field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.opta_competition_id
   * - **Tab**: Data (Opta)
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  opta_competition_id: prismic.KeyTextField;

  /**
   * Opta Season ID field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.opta_season_id
   * - **Tab**: Data (Opta)
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  opta_season_id: prismic.KeyTextField;

  /**
   * Opta Enabled field in *Tournament*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tournament.opta_enabled
   * - **Tab**: Data (Opta)
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  opta_enabled: prismic.BooleanField /**
   * Show in Navigation field in *Tournament*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tournament.show_in_navigation
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */;
  show_in_navigation: prismic.BooleanField;

  /**
   * Navigation Order field in *Tournament*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Order in navigation (lower numbers appear first)
   * - **API ID Path**: tournament.navigation_order
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  navigation_order: prismic.NumberField;

  /**
   * Navigation Image field in *Tournament*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.nav_image
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  nav_image: prismic.ImageField<never>;

  /**
   * Navigation Description field in *Tournament*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tournament.navigation_description
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  navigation_description: prismic.KeyTextField;
}

/**
 * Tournament document from Prismic
 *
 * - **API ID**: `tournament`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TournamentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TournamentDocumentData>,
    "tournament",
    Lang
  >;

/**
 * Item in *Website → Footer Menus → Menu Links*
 */
export interface WebsiteDocumentDataFooterMenusMenuLinksItem {
  /**
   * Link Text field in *Website → Footer Menus → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link text
   * - **API ID Path**: website.footer_menus[].menu_links[].link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link URL field in *Website → Footer Menus → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: URL or path
   * - **API ID Path**: website.footer_menus[].menu_links[].link_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_url: prismic.KeyTextField;

  /**
   * External Link field in *Website → Footer Menus → Menu Links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: website.footer_menus[].menu_links[].is_external
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_external: prismic.BooleanField;
}

/**
 * Item in *Website → Footer Menus*
 */
export interface WebsiteDocumentDataFooterMenusItem {
  /**
   * Menu Title field in *Website → Footer Menus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Footer menu title
   * - **API ID Path**: website.footer_menus[].menu_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_title: prismic.KeyTextField;

  /**
   * Menu Links field in *Website → Footer Menus*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: website.footer_menus[].menu_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_links: prismic.NestedGroupField<
    Simplify<WebsiteDocumentDataFooterMenusMenuLinksItem>
  >;
}

/**
 * Item in *Website → Where to watch partners*
 */
export interface WebsiteDocumentDataWhereToWatchPartnersItem {
  /**
   * Broadcast Partner field in *Website → Where to watch partners*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: website.where_to_watch_partners[].broadcast_partner
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  broadcast_partner: ContentRelationshipFieldWithData<
    [
      {
        id: "broadcast_partners";
        fields: [
          "name",
          "logo_white",
          "logo",
          "icon_logo",
          "logo_on_primary",
          "color_primary",
          "color_secondary",
          "streaming_link",
        ];
      },
    ]
  >;
}

/**
 * Content for Website documents
 */
interface WebsiteDocumentData {
  /**
   * Footer Menus field in *Website*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: website.footer_menus[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_menus: prismic.GroupField<
    Simplify<WebsiteDocumentDataFooterMenusItem>
  > /**
   * More Info Mode field in *Website*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: website.more_info_mode
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  more_info_mode: prismic.SelectField<"Recent News" | "Where to watch">;

  /**
   * Where to watch partners field in *Website*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: website.where_to_watch_partners[]
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  where_to_watch_partners: prismic.GroupField<
    Simplify<WebsiteDocumentDataWhereToWatchPartnersItem>
  >;
}

/**
 * Website document from Prismic
 *
 * - **API ID**: `website`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WebsiteDocumentData>,
    "website",
    Lang
  >;

export type AllDocumentTypes =
  | AwardsDocument
  | BlogDocument
  | BroadcastPartnersDocument
  | FaqSectionDocument
  | ImageWithTextDocument
  | MatchDocument
  | PageDocument
  | PlayerDocument
  | PolicyDocument
  | SponsorDocument
  | TeamDocument
  | TeamMemberDocument
  | TournamentDocument
  | WebsiteDocument;

/**
 * Item in *AccordionSection → Default → Primary → Items*
 */
export interface AccordionSectionSliceDefaultPrimaryItemsItem {
  /**
   * Question field in *AccordionSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *AccordionSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *AccordionSection → Default → Primary*
 */
export interface AccordionSectionSliceDefaultPrimary {
  /**
   * Title field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Items field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<AccordionSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for AccordionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AccordionSection*
 */
type AccordionSectionSliceVariation = AccordionSectionSliceDefault;

/**
 * AccordionSection Shared Slice
 *
 * - **API ID**: `accordion_section`
 * - **Description**: AccordionSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSectionSlice = prismic.SharedSlice<
  "accordion_section",
  AccordionSectionSliceVariation
>;

/**
 * Item in *CallToAction → Default → Primary → Description*
 */
export interface CallToActionSliceDefaultPrimaryDescriptionItem {
  /**
   * Text field in *CallToAction → Default → Primary → Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.description[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.description[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  description: prismic.GroupField<
    Simplify<CallToActionSliceDefaultPrimaryDescriptionItem>
  >;

  /**
   * Button Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Alignment field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Variant field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: hero_section.default.primary.variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"default" | "secondary", "filled">;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Title field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image Position field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: image_with_text.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"Left" | "Right", "filled">;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation = ImageWithTextSliceDefault;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Item in *InfoCards → Default → Primary → Cards*
 */
export interface InfoCardsSliceDefaultPrimaryCardsItem {
  /**
   * Subtitle field in *InfoCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.cards[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *InfoCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *InfoCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *InfoCards → Default → Primary*
 */
export interface InfoCardsSliceDefaultPrimary {
  /**
   * Title field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Footnote field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.footnote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footnote: prismic.KeyTextField;

  /**
   * Button Link field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Cards Title field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.cards_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cards_title: prismic.KeyTextField;

  /**
   * Cards field in *InfoCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<InfoCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for InfoCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoCards*
 */
type InfoCardsSliceVariation = InfoCardsSliceDefault;

/**
 * InfoCards Shared Slice
 *
 * - **API ID**: `info_cards`
 * - **Description**: InfoCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardsSlice = prismic.SharedSlice<
  "info_cards",
  InfoCardsSliceVariation
>;

/**
 * Item in *LeadershipGrid → Default → Primary → Members*
 */
export interface LeadershipGridSliceDefaultPrimaryMembersItem {
  /**
   * Member field in *LeadershipGrid → Default → Primary → Members*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.members[].member
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  member: ContentRelationshipFieldWithData<
    [
      {
        id: "team_member";
        fields: [
          "name",
          "role",
          "bio",
          "headshot",
          "display_order",
          "department",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *LeadershipGrid → Default → Primary*
 */
export interface LeadershipGridSliceDefaultPrimary {
  /**
   * Title field in *LeadershipGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *LeadershipGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Section ID field in *LeadershipGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Scroll Link field in *LeadershipGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.scroll_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  scroll_link: prismic.KeyTextField;

  /**
   * Members field in *LeadershipGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_grid.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  members: prismic.GroupField<
    Simplify<LeadershipGridSliceDefaultPrimaryMembersItem>
  >;
}

/**
 * Default variation for LeadershipGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadershipGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadershipGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LeadershipGrid*
 */
type LeadershipGridSliceVariation = LeadershipGridSliceDefault;

/**
 * LeadershipGrid Shared Slice
 *
 * - **API ID**: `leadership_grid`
 * - **Description**: LeadershipGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadershipGridSlice = prismic.SharedSlice<
  "leadership_grid",
  LeadershipGridSliceVariation
>;

/**
 * Item in *Partners → Default → Primary → Logos*
 */
export interface PartnersSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Partners → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Title field in *Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Columns field in *Partners → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 2
   * - **API ID Path**: partners.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"2" | "3" | "4" | "6", "filled">;

  /**
   * Logos field in *Partners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<PartnersSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Title field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Alignment field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"Left" | "Center" | "Right">;

  /**
   * Max Width field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.max_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  max_width: prismic.SelectField<"sm" | "md" | "lg" | "full">;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AwardsDocument,
      AwardsDocumentData,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogDocumentDataMatchesItem,
      BlogDocumentDataTeamsItem,
      BroadcastPartnersDocument,
      BroadcastPartnersDocumentData,
      FaqSectionDocument,
      FaqSectionDocumentData,
      FaqSectionDocumentDataFaqsItem,
      ImageWithTextDocument,
      ImageWithTextDocumentData,
      MatchDocument,
      MatchDocumentData,
      MatchDocumentDataBroadcastsItem,
      MatchDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PlayerDocument,
      PlayerDocumentData,
      PolicyDocument,
      PolicyDocumentData,
      SponsorDocument,
      SponsorDocumentData,
      TeamDocument,
      TeamDocumentData,
      TeamDocumentDataTournamentsItem,
      TeamMemberDocument,
      TeamMemberDocumentData,
      TournamentDocument,
      TournamentDocumentData,
      TournamentDocumentDataSlicesSlice,
      TournamentDocumentDataMatchesItem,
      TournamentDocumentDataAwardsItem,
      WebsiteDocument,
      WebsiteDocumentData,
      WebsiteDocumentDataFooterMenusMenuLinksItem,
      WebsiteDocumentDataFooterMenusItem,
      WebsiteDocumentDataWhereToWatchPartnersItem,
      AllDocumentTypes,
      AccordionSectionSlice,
      AccordionSectionSliceDefaultPrimaryItemsItem,
      AccordionSectionSliceDefaultPrimary,
      AccordionSectionSliceVariation,
      AccordionSectionSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimaryDescriptionItem,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      InfoCardsSlice,
      InfoCardsSliceDefaultPrimaryCardsItem,
      InfoCardsSliceDefaultPrimary,
      InfoCardsSliceVariation,
      InfoCardsSliceDefault,
      LeadershipGridSlice,
      LeadershipGridSliceDefaultPrimaryMembersItem,
      LeadershipGridSliceDefaultPrimary,
      LeadershipGridSliceVariation,
      LeadershipGridSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryLogosItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
