// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  community_champions: dynamic(() => import("./CommunityChampions")),
  divider: dynamic(() => import("./Divider")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  news_list: dynamic(() => import("./NewsList")),
  subpage_hero: dynamic(() => import("./SubpageHero")),
  text_block: dynamic(() => import("./TextBlock")),
};
