// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_section: dynamic(() => import("./AccordionSection")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero_section: dynamic(() => import("./HeroSection")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  partners: dynamic(() => import("./Partners")),
  text_block: dynamic(() => import("./TextBlock")),
};
